In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats
import re
import sys 
import statsmodels.stats.multitest
#sys.path.append('C:\\Users\\brittany\\henderson\\GitHub\\GBM_for_CPTAC\\')
#import cis_functions as f
#sys.path.append('C:\\Users\\Lindsey\\Documents\\GitHub\\WhenMutationsDontMatter\\')
#import plot_utils as p


import cptac
import cptac.utils as u

# GBM

In [2]:

df = pd.read_csv('GBM_EGFR_other.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df

      Comparison         Slope     R_squared       P_value
0         PHLDA1  5.368720e-01  6.591140e-01  9.317624e-27
1          SOCS2  2.909121e-01  3.312017e-01  5.912447e-11
2         GPRIN3 -1.968711e-01  2.860431e-01  2.089433e-09
3           NFIA  2.349343e-01  2.788730e-01  3.609065e-09
4          MEOX2  2.938146e-01  2.893869e-01  1.114403e-08
...          ...           ...           ...           ...
10063   ALDH16A1 -2.107089e-05  6.175566e-09  9.993529e-01
10064      ARPIN -9.183936e-06  1.015793e-09  9.997776e-01
10065    POMGNT1 -3.929534e-06  5.430333e-10  9.998081e-01
10066   SERPINA4  9.564123e-06  2.820304e-10  9.998617e-01
10067      AKAP7  7.816406e-08  2.411407e-14  9.999987e-01

[10068 rows x 4 columns]

# Kidney

In [3]:
df2 = pd.read_csv('Kidney_EGFR_other.csv')

In [4]:
df2 = df2.drop(['Unnamed: 0'], axis=1)
df2

      Comparison     Slope     R_squared       P_value
0        SLC16A3  1.948890  8.714648e-01  1.800478e-87
1       NDUFA4L2  3.199722  8.652865e-01  1.637846e-85
2           PYGL  1.671819  8.476211e-01  2.269840e-80
3           NOL3  1.657460  8.303670e-01  6.801961e-76
4       PPP1R13L  0.941977  8.250937e-01  1.289226e-74
...          ...       ...           ...           ...
10615      DPY30 -0.000034  2.197312e-08  9.983633e-01
10616       NXF1 -0.000016  8.603673e-09  9.989758e-01
10617       SDC3  0.000369  1.693425e-07  9.992284e-01
10618        WRB  0.000056  8.595204e-09  9.993322e-01
10619      RAB4B  0.000005  3.455657e-10  9.997947e-01

[10620 rows x 4 columns]

In [5]:
Gbm_kidney = pd.merge(df, df2, on="Comparison", how = "outer")
Gbm_kidney = Gbm_kidney.rename(columns={"Slope_x": "Slope_Gbm", "R_squared_x": "R_squared_gbm","P_value_x": "P_value_Gbm" })
Gbm_kidney = Gbm_kidney.rename(columns={"Slope_y": "Slope_kidney", "R_squared_y": "R_squared_kidney","P_value_y": "P_value_kidney" })
#Gbm_kidney.to_csv("GBM_Kidney_EGFR_all.csv")
Gbm_kidney

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN
...,...,...,...,...,...,...,...
11880,HIST1H2BB,NaN,NaN,NaN,-0.013281,0.000122,9.775112e-01
11881,POF1B,NaN,NaN,NaN,0.003014,0.000004,9.777676e-01
11882,GPR18,NaN,NaN,NaN,-0.024345,0.000101,9.795530e-01
11883,CD79A,NaN,NaN,NaN,0.004027,0.000014,9.857007e-01
11884,CEACAM7,NaN,NaN,NaN,0.004111,0.000011,9.902006e-01

# Endometrial

In [6]:
df3 = pd.read_csv("Endo_EGFR_other.csv")
df3 = df3.drop(['Unnamed: 0'], axis=1)
df3

     Comparison     Slope     R_squared       P_value
0         CYLC1  2.205497  1.000000e+00  0.000000e+00
1        PGRMC1  0.826272  4.557369e-01  1.716216e-20
2          ROR2  0.696391  4.305630e-01  4.372766e-19
3        RHBDF1  0.514847  4.143455e-01  3.271381e-18
4          GPX8  0.819246  4.125182e-01  4.089941e-18
...         ...       ...           ...           ...
9946      INTS2  0.000035  9.473855e-09  9.990762e-01
9947   C11orf68  0.000081  9.173637e-09  9.990909e-01
9948      SPON1 -0.000177  7.263106e-09  9.991911e-01
9949      HYLS1 -0.000089  2.535062e-08  9.992984e-01
9950      UFSP2  0.000020  2.216054e-09  9.995532e-01

[9951 rows x 4 columns]

In [7]:
pancan = pd.merge(Gbm_kidney, df3, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Endo", "R_squared": "R_squared_Endo","P_value": "P_value_Endo" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,6.844122e-02,0.001538
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,1.906803e-02,0.123080
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,4.875856e-02,0.011583
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,3.221808e-03,0.499205
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
12388,C11orf16,NaN,NaN,NaN,NaN,NaN,NaN,-0.003030,1.331041e-05,0.983152
12389,TTC21A,NaN,NaN,NaN,NaN,NaN,NaN,-0.002420,4.236107e-06,0.987656
12390,AMPD1,NaN,NaN,NaN,NaN,NaN,NaN,0.004010,3.406916e-05,0.988110
12391,HOXD11,NaN,NaN,NaN,NaN,NaN,NaN,0.001252,5.117517e-07,0.997752
12392,KLK12,NaN,NaN,NaN,NaN,NaN,NaN,0.000834,7.915830e-08,0.998129

# Ovarian

In [8]:
df_Ovar = pd.read_csv("Ovar_EGFR_other.csv")
df_Ovar = df_Ovar.drop(['Unnamed: 0'], axis=1)
df_Ovar

     Comparison         Slope     R_squared       P_value
0           DPT  1.795847e+00  4.503296e-01  8.751882e-15
1            CP  1.174599e+00  4.445998e-01  1.486631e-14
2          AMBP  1.273994e+00  4.351269e-01  3.528593e-14
3           OGN  2.412038e+00  4.301344e-01  5.533366e-14
4        ABI3BP  1.881803e+00  4.292029e-01  6.015382e-14
...         ...           ...           ...           ...
9674       PHYH  4.817077e-05  1.263137e-09  9.997157e-01
9675     PCMTD1 -2.887423e-05  1.246684e-09  9.997176e-01
9676    TMEM175  2.866794e-05  4.372342e-10  9.998560e-01
9677     CCDC94 -1.616499e-05  2.495293e-10  9.998736e-01
9678       UBA3 -7.442072e-07  1.711304e-12  9.999895e-01

[9679 rows x 4 columns]

In [9]:
pancan = pd.merge(pancan, df_Ovar, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Ovar", "R_squared": "R_squared_Ovar","P_value": "P_value_Ovar" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,0.068441,0.001538,0.840646,2.474298e-01,0.002761
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,0.019068,0.123080,NaN,NaN,NaN
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,0.048759,0.011583,0.131152,1.141540e-02,0.302755
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,0.003222,0.499205,0.418724,1.379906e-01,0.000112
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13584,STARD9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001737,3.015707e-06,0.986110
13585,CENPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.001439,3.474135e-06,0.988723
13586,MROH8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002439,2.951149e-06,0.992186
13587,TMEM69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001884,9.429241e-07,0.993313
13588,CCDC94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000016,2.495293e-10,0.999874

# BRCA

In [10]:
df_Brca = pd.read_csv("Brca_EGFR_other.csv")
df_Brca = df_Brca.drop(['Unnamed: 0'], axis=1)
df_Brca

     Comparison     Slope     R_squared       P_value
0          MPP6  0.429836  4.201654e-01  4.834438e-15
1         CPNE8  0.422036  3.800139e-01  2.229263e-13
2        CRYBG3  0.328675  3.720964e-01  4.612176e-13
3          PHC3 -0.358139  3.638555e-01  9.738761e-13
4         GATA3 -0.871909  3.586947e-01  1.547846e-12
...         ...       ...           ...           ...
9149     SEMA4C  0.000186  6.404153e-08  9.978583e-01
9150    ZKSCAN5  0.000208  4.283453e-08  9.983862e-01
9151      EIF2A  0.000048  1.258126e-08  9.990508e-01
9152      YARS2 -0.000056  8.771033e-09  9.992074e-01
9153    CSNK1G1  0.000042  4.541596e-09  9.994503e-01

[9154 rows x 4 columns]

In [11]:
pancan = pd.merge(pancan, df_Brca, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Brca", "R_squared": "R_squared_Brca","P_value": "P_value_Brca" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,0.068441,0.001538,0.840646,0.247430,0.002761,0.363866,0.133077,0.000190
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,0.019068,0.123080,NaN,NaN,NaN,NaN,NaN,NaN
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,0.048759,0.011583,0.131152,0.011415,0.302755,-0.063316,0.011106,0.262337
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,0.003222,0.499205,0.418724,0.137991,0.000112,-0.093636,0.013491,0.216394
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14981,ADARB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.018408,0.000137,0.939896
14982,GTF2H2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002232,0.000043,0.944789
14983,FAM134C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003038,0.000017,0.965252
14984,DDTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002766,0.000013,0.969627
14985,C18orf63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004057,0.000006,0.980937

# Luad

In [12]:
df_Luad = pd.read_csv("Luad_EGFR_other.csv")
df_Luad = df_Luad.drop(['Unnamed: 0'], axis=1)
df_Luad

     Comparison     Slope     R_squared       P_value
0        NUDCD3  0.271002  3.104883e-01  1.313609e-18
1          GGCT  0.621866  3.068076e-01  2.304633e-18
2        LANCL2  0.337830  2.933769e-01  1.749608e-17
3       TAX1BP1  0.476434  2.887110e-01  3.507529e-17
4        PGRMC1  0.422994  2.598541e-01  2.354858e-15
...         ...       ...           ...           ...
9689   SLC7A6OS -0.000039  4.005150e-09  9.992709e-01
9690      ERAP1 -0.000050  3.512770e-09  9.993172e-01
9691     RNASEL  0.000014  8.718979e-10  9.996598e-01
9692     CARD19 -0.000018  8.320102e-10  9.996677e-01
9693    SLC22A3  0.000005  2.889543e-11  9.999525e-01

[9694 rows x 4 columns]

In [13]:
pancan = pd.merge(pancan, df_Luad, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_Luad", "R_squared": "R_squared_Luad","P_value": "P_value_Luad" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,Slope_Ovar,R_squared_Ovar,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,0.068441,0.001538,0.840646,0.247430,0.002761,0.363866,0.133077,0.000190,0.236356,5.799533e-02,0.001128
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,0.019068,0.123080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,0.048759,0.011583,0.131152,0.011415,0.302755,-0.063316,0.011106,0.262337,-0.136077,3.795374e-02,0.004507
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,0.003222,0.499205,0.418724,0.137991,0.000112,-0.093636,0.013491,0.216394,NaN,NaN,NaN
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17791,FOXN2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.005709,2.076183e-05,0.952695
17792,ARMC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003179,1.997181e-05,0.953740
17793,FAM83A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.004449,1.370670e-05,0.965752
17794,MICALCL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001182,1.744562e-06,0.989023
17795,TTLL8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.001256,7.902525e-07,0.993636

# HNSCC

In [14]:
df_hnscc = pd.read_csv("Hnscc_EGFR_other.csv")
df_hnscc = df_hnscc.drop(['Unnamed: 0'], axis=1)
df_hnscc

      Comparison     Slope     R_squared       P_value
0         LANCL2  0.454531  5.509016e-01  2.051725e-32
1           TPBG  0.403111  3.907073e-01  1.105601e-20
2         PHLDA2  0.461051  3.783922e-01  6.533170e-20
3          FSCN1  0.407948  3.477648e-01  4.688474e-18
4         PHLDA3  0.360058  3.469504e-01  5.238621e-18
...          ...       ...           ...           ...
10598     FER1L5  0.000066  1.064363e-08  9.990596e-01
10599       ICE2  0.000037  9.154883e-09  9.991346e-01
10600    POMGNT2 -0.000043  5.163461e-09  9.994426e-01
10601      ANOS1  0.000045  2.965621e-09  9.996378e-01
10602       F8A2 -0.000006  6.013037e-10  9.997408e-01

[10603 rows x 4 columns]

In [15]:
pancan = pd.merge(pancan, df_hnscc, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_hnscc", "R_squared": "R_squared_hnscc","P_value": "P_value_hnscc" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,...,P_value_Ovar,Slope_Brca,R_squared_Brca,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad,Slope_hnscc,R_squared_hnscc,P_value_hnscc
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,0.068441,0.001538,...,0.002761,0.363866,0.133077,0.000190,0.236356,0.057995,0.001128,0.329068,2.173712e-01,5.426160e-11
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,0.019068,0.123080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022552,8.242128e-04,8.121430e-01
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,0.048759,0.011583,...,0.302755,-0.063316,0.011106,0.262337,-0.136077,0.037954,0.004507,-0.145481,6.426076e-02,2.510702e-03
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,0.003222,0.499205,...,0.000112,-0.093636,0.013491,0.216394,NaN,NaN,NaN,-0.189774,8.055313e-02,1.234413e-04
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.209414,1.718062e-01,2.336687e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18191,HR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.035388,9.886877e-05,9.797454e-01
18192,IL1F10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004644,1.890131e-05,9.828295e-01
18193,ASCL2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002109,8.203420e-06,9.886877e-01
18194,C10orf99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000809,1.414553e-06,9.893693e-01
18195,FER1L5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000066,1.064363e-08,9.990596e-01

# Colon

In [16]:
df_colon = pd.read_csv("Colon_EGFR_other.csv")
df_colon = df_colon.drop(['Unnamed: 0'], axis=1)
df_colon

     Comparison     Slope     R_squared       P_value
0          SCG2  1.862523  4.107253e-01  3.568355e-24
1          RAE1 -0.524313  3.898431e-01  1.091653e-22
2         DDX27 -0.763667  3.814268e-01  4.195557e-22
3         XRCC6 -0.505202  3.777787e-01  7.478485e-22
4          CHD4 -0.523516  3.751070e-01  1.139570e-21
...         ...       ...           ...           ...
7232      TUSC5 -0.001356  1.870058e-06  9.972142e-01
7233     FCGR3A  0.000560  8.542211e-08  9.980559e-01
7234     GEMIN4  0.000105  2.105097e-08  9.984233e-01
7235      ARID2 -0.000120  1.514682e-08  9.987953e-01
7236      ASCC2 -0.000012  3.011261e-10  9.998069e-01

[7237 rows x 4 columns]

In [17]:
pancan = pd.merge(pancan, df_colon, on="Comparison", how = "outer")
pancan = pancan.rename(columns={"Slope": "Slope_colon", "R_squared": "R_squared_colon","P_value": "P_value_colon" })
pancan

,Comparison,Slope_Gbm,R_squared_gbm,P_value_Gbm,Slope_kidney,R_squared_kidney,P_value_kidney,Slope_Endo,R_squared_Endo,P_value_Endo,...,P_value_Brca,Slope_Luad,R_squared_Luad,P_value_Luad,Slope_hnscc,R_squared_hnscc,P_value_hnscc,Slope_colon,R_squared_colon,P_value_colon
0,PHLDA1,0.536872,0.659114,9.317624e-27,0.189696,0.081886,5.235390e-05,0.304536,0.068441,0.001538,...,0.000190,0.236356,0.057995,0.001128,0.329068,0.217371,5.426160e-11,0.055226,1.808419e-03,7.407001e-01
1,SOCS2,0.290912,0.331202,5.912447e-11,-0.385206,0.599567,1.430341e-02,0.174235,0.019068,0.123080,...,NaN,NaN,NaN,NaN,0.022552,0.000824,8.121430e-01,NaN,NaN,NaN
2,GPRIN3,-0.196871,0.286043,2.089433e-09,-0.032602,0.005102,3.223231e-01,0.168797,0.048759,0.011583,...,0.262337,-0.136077,0.037954,0.004507,-0.145481,0.064261,2.510702e-03,0.183737,3.481000e-02,1.239463e-02
3,NFIA,0.234934,0.278873,3.609065e-09,0.241707,0.276612,3.410149e-15,0.052400,0.003222,0.499205,...,0.216394,NaN,NaN,NaN,-0.189774,0.080553,1.234413e-04,0.481289,1.874984e-01,5.423213e-10
4,MEOX2,0.293815,0.289387,1.114403e-08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-0.209414,0.171806,2.336687e-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18272,GPX6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.068721,7.938315e-04,9.426403e-01
18273,UGT2B15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.033471,4.293094e-04,9.578051e-01
18274,ATP5G1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006282,9.149335e-06,9.663514e-01
18275,REG1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.005225,6.352281e-06,9.902506e-01
18276,C14orf1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000533,1.533484e-07,9.958490e-01

In [18]:
pancan.to_csv("pancan_EGFR_other.csv")