In [2]:
import pandas as pd
import plot_utils 
import numpy as np
import math

In [3]:
trans = pd.read_csv('~/WhenMutationsDontMatter/PIK3CA/csv_files/proteomics.csv', index_col=0)
trans.head()

,Difference_In_Median_Brca,P_Value_Brca,Difference_In_Median_Endo,P_Value_Endo,Difference_In_Median,P_Value
A2ML1,-1.26120,0.165194,1.10585,0.037044,NaN,NaN
AADAT,-1.33200,0.027477,-0.18535,0.690613,NaN,NaN
AAGAB,-0.09455,0.909622,0.24350,0.139632,0.1390,0.039189
AASDHPPT,0.51445,0.003620,-0.10590,0.428884,-0.0628,0.973515
AATF,-0.16905,0.042271,-0.18170,0.915482,0.0250,0.568821

In [4]:
def significant(row):
    if row['P_Value_Brca'] > .05:
        row['P_Value_Brca'] = np.nan
        row['Difference_In_Median_Brca'] = np.nan

    if row['P_Value_Endo'] > .05:
        row['P_Value_Endo'] = np.nan
        row['Difference_In_Median_Endo'] = np.nan
        

    if row['P_Value'] > .05:
        row['P_Value'] = np.nan
        row['Difference_In_Median'] = np.nan
        
    if math.isnan(row['P_Value']):
        row['P_Value'] = np.nan
        row['Difference_In_Median'] = np.nan

    return row

In [5]:
sig = trans.apply(significant, axis=1)
sig.head()

,Difference_In_Median_Brca,P_Value_Brca,Difference_In_Median_Endo,P_Value_Endo,Difference_In_Median,P_Value
A2ML1,NaN,NaN,1.10585,0.037044,NaN,NaN
AADAT,-1.33200,0.027477,NaN,NaN,NaN,NaN
AAGAB,NaN,NaN,NaN,NaN,0.139,0.039189
AASDHPPT,0.51445,0.003620,NaN,NaN,NaN,NaN
AATF,-0.16905,0.042271,NaN,NaN,NaN,NaN

In [6]:
sig.to_csv("~/WhenMutationsDontMatter/PIK3CA/csv_files/proteomics_sig.csv")